"""Sync schema and remove mocks

Revision ID: d994738412fa
Revises: ddef133af530
Create Date: 2026-01-20 19:56:21.291104
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd994738412fa'
down_revision = 'ddef133af530'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
