"""change_target_conversion_to_string

Revision ID: ddef133af530
Revises: 0003_nurture_email_fields
Create Date: 2026-01-20 02:10:58.756772
"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'ddef133af530'
down_revision = '0003_nurture_email_fields'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_app_settings_id'), 'app_settings', ['id'], unique=False)
    op.alter_column('assets', 'content_text',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.create_index(op.f('ix_assets_id'), 'assets', ['id'], unique=False)
    op.alter_column('campaigns', 'icp_company_size',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('campaigns', 'target_conversion',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('campaigns', 'linked_in_post',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.create_index(op.f('ix_campaigns_id'), 'campaigns', ['id'], unique=False)
    op.alter_column('email_logs', 'body',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.alter_column('email_logs', 'error_message',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('email_logs', 'scheduled_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('email_logs', 'sent_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.create_index(op.f('ix_email_logs_id'), 'email_logs', ['id'], unique=False)
    op.create_index(op.f('ix_email_logs_sequence_id'), 'email_logs', ['sequence_id'], unique=False)
    op.create_index(op.f('ix_email_logs_step_id'), 'email_logs', ['step_id'], unique=False)
    op.alter_column('email_templates', 'body',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.create_index(op.f('ix_email_templates_id'), 'email_templates', ['id'], unique=False)
    op.alter_column('landing_pages', 'html_content',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.create_index(op.f('ix_landing_pages_id'), 'landing_pages', ['id'], unique=False)
    op.create_index(op.f('ix_lead_magnets_id'), 'lead_magnets', ['id'], unique=False)
    op.create_index(op.f('ix_leads_campaign_id'), 'leads', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_leads_id'), 'leads', ['id'], unique=False)
    op.create_index(op.f('ix_leads_landing_page_id'), 'leads', ['landing_page_id'], unique=False)
    op.create_index(op.f('ix_leads_lead_magnet_id'), 'leads', ['lead_magnet_id'], unique=False)
    op.create_index(op.f('ix_nurture_sequences_id'), 'nurture_sequences', ['id'], unique=False)
    op.create_index(op.f('ix_nurture_sequences_lead_magnet_id'), 'nurture_sequences', ['lead_magnet_id'], unique=False)
    op.alter_column('nurture_steps', 'body',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.create_index(op.f('ix_nurture_steps_id'), 'nurture_steps', ['id'], unique=False)
    op.create_index(op.f('ix_nurture_steps_order'), 'nurture_steps', ['order'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_nurture_steps_order'), table_name='nurture_steps')
    op.drop_index(op.f('ix_nurture_steps_id'), table_name='nurture_steps')
    op.alter_column('nurture_steps', 'body',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_index(op.f('ix_nurture_sequences_lead_magnet_id'), table_name='nurture_sequences')
    op.drop_index(op.f('ix_nurture_sequences_id'), table_name='nurture_sequences')
    op.drop_index(op.f('ix_leads_lead_magnet_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_landing_page_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_campaign_id'), table_name='leads')
    op.drop_index(op.f('ix_lead_magnets_id'), table_name='lead_magnets')
    op.drop_index(op.f('ix_landing_pages_id'), table_name='landing_pages')
    op.alter_column('landing_pages', 'html_content',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_index(op.f('ix_email_templates_id'), table_name='email_templates')
    op.alter_column('email_templates', 'body',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_index(op.f('ix_email_logs_step_id'), table_name='email_logs')
    op.drop_index(op.f('ix_email_logs_sequence_id'), table_name='email_logs')
    op.drop_index(op.f('ix_email_logs_id'), table_name='email_logs')
    op.alter_column('email_logs', 'sent_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('email_logs', 'scheduled_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('email_logs', 'error_message',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('email_logs', 'body',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_index(op.f('ix_campaigns_id'), table_name='campaigns')
    op.alter_column('campaigns', 'linked_in_post',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('campaigns', 'target_conversion',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('campaigns', 'icp_company_size',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_assets_id'), table_name='assets')
    op.alter_column('assets', 'content_text',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_app_settings_id'), table_name='app_settings')
    # ### end Alembic commands ###
